### ISSUE TITLE
missing crafting recipes files

### ISSUE THREAD

**Issue by augugusto** [bladecoding/isaac-bagofcrafting#1]
the code seems to look for all the recipes as individual files at F:/bag_of_crafting_recipes but those files are not uploaded to the repo. could we have those? I'm trying to  make a script where i can tell it what is on the flor and it tells me all i can craft (and hopefully sort best to worst)

**Comment by bladecoding** [comment]
Those files aren't needed. They are the precomputed recipes which were only used for initial validity testing. You only need this to calculate the item for a given recipe

```
import fs = require('fs');
import { BagOfCrafting } from './BagOfCrafting';
import { XmlParser } from './XmlParser';

let pools = XmlParser.loadPools(fs.readFileSync('assets/itempools.xml', 'utf8'));
let meta = XmlParser.loadMeta(fs.readFileSync('assets/items_metadata.xml', 'utf8'));
let bc = new BagOfCrafting(pools, meta);

let itemIdForRecipe = bc.calculate([1, 2, 3, 6, 13, 18, 24, 24]);
```

The precomputed recipes are [here](https://github.com/bladecoding/isaac-bagofcrafting-recipes/tree/main/assets/recipes) but they are 90MB of text so I wouldn't recommend using them and instead use `BagOfCrafting.calculate`.

**Comment by augugusto** [comment]
great. closing the issue. if i manage to make it, I'll open a pull request with that code, a few comments on index.ts to clarify usage, and a readme.md
